# Generated by Django 2.2.7 on 2020-05-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='sus',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
