# Generated by Django 2.2.7 on 2020-05-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_playlist_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='quality',
            field=models.CharField(choices=[('TE', 'Terrible'), ('BA', 'Bad'), ('OK', 'Neutral'), ('GO', 'Good'), ('EX', 'Excellent')], default='OK', max_length=2),
        ),
    ]
