# Generated by Django 2.2.7 on 2020-06-14 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_auto_20200614_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='quality',
            field=models.CharField(choices=[('TE', 'Terrible'), ('BA', 'Bad'), ('OK', 'Neutral'), ('GO', 'Good'), ('EX', 'Excellent'), ('TB', 'Tba')], default='TB', max_length=2),
        ),
    ]
