# Generated by Django 2.2.7 on 2020-06-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_auto_20200614_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='created',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='modified',
        ),
    ]
