# Generated by Django 2.2.7 on 2020-06-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_auto_20200614_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='seven_day_quality',
            field=models.CharField(choices=[('TE', 'Terrible'), ('BA', 'Bad'), ('OK', 'Neutral'), ('GO', 'Good'), ('EX', 'Excellent'), ('TB', 'Tba')], default='TB', max_length=2),
        ),
    ]
