# Generated by Django 2.2.7 on 2020-06-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_playlist_seven_day_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='qualities_list',
            field=models.CharField(max_length=50000, null=True),
        ),
    ]
