# Generated by Django 2.2.7 on 2020-06-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_playlist_qualities_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='avg_dance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playlist',
            name='avg_energy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playlist',
            name='avg_instru',
            field=models.FloatField(default=0),
        ),
    ]
