# Generated by Django 2.2.7 on 2020-06-25 01:37

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('quotes', '0015_playlist_avg_valence'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
