# Generated by Django 3.0.6 on 2020-06-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0017_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='picture_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
