# Generated by Django 3.0.6 on 2020-06-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0018_playlist_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
