# Generated by Django 3.0.6 on 2020-06-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0019_playlist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='photo_blue',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='photo_green',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='photo_red',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
