# Generated by Django 3.0.6 on 2020-06-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0020_auto_20200630_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='photo_blue',
            field=models.FloatField(default=78),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='photo_green',
            field=models.FloatField(default=255),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='photo_red',
            field=models.FloatField(default=125),
        ),
    ]
