# Generated by Django 3.0.6 on 2020-08-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0021_auto_20200630_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='qualities_list',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='picture_url',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
